### PR TITLE
Graphics.sprite.setAlwaysRedraw to false by default

### PR DESCRIPTION
**Pull request by simjnd**
In [**Noble.lua** at line 91](https://github.com/NobleRobot/NobleEngine/blob/10d3ca03382d93b1726fd73c175f45c1bdd7d970/Noble.lua#L91) you set `Graphics.sprite.setAlwaysRedraw(true)` when the [**SDK Documentation** specifies](https://sdk.play.date/1.12.3/Inside%20Playdate.html#f-graphics.sprite.setAlwaysRedraw) that it *can* be faster only in very specific circumstances (namely when you have a ton of sprites moving at once.

I am not sure if there were any reasons why you opted-in, but I think it would be wiser to have this set to false by default, so that all the simpler projects that rely on NobleEngine can benefit from the battery and performance improvements of fewer draw calls, and only when they reach this specific bottleneck can they opt-in to this behaviour, as it is with the default SDK.

### CODE REVIEW

**Comment by simjnd** [comment]
It's definitely a good idea to offer a good explanation of the feature in the docs. Since sprites automatically handle the dirty-tracking and optimize for the least amount of draw calls necessary, the explanation should probably push users into using sprites for most things they want to render this way we can avoid them having to worry about this.

Instead of putting in `Noble.new()` how would you feel about maybe creating a `Noble.config()` method that can take a table with keys to configure certains parameters?

```lua
Noble.config({
  setAlwaysRedraw = true,
  showFPS = true
})

Noble.new(...)
```

This could serve for future more advanced configuration, for instance if you want to configure the threshold used to determine whether a button is held or not (say instead of 3 frames you want a threshold of 5 frames), or other things I can't think of at the moment.

**Comment by Mark-LaCroix** [comment]
I've gone in and updated Noble.lua to add a configuration API, which allows user to set these values:

```{
	defaultTransitionDuration = 1,
	defaultTransitionHoldDuration = 0.2,
	defaultTransitionType = Noble.TransitionType.DIP_TO_BLACK,
	enableDebugBonkChecking = false,
	alwaysRedraw = true,
}```

I did leave `alwaysRedraw` as true for now, just to avoid any breaking changes (although this does introduce a smaller one), but it should give users control over it at least. I suspect this will get further updates in the future.

**Comment by Mark-LaCroix** [comment]
I'm very happy that your PR inspired this change, btw!

**Comment by GammaGames** [comment]
I still think false as default would be the best. Understanding how sprites are updated is often one of the first approaches people try to optimize and pretty much all tutorials are geared toward using sprites this way. Overriding the SDK default just doesn't seem smart.

Also, literally everyone I've seen using Noble change to the SDK default because of the performance boost.

**Pull request merged**
