### PR TITLE
new transition system

### PR DESCRIPTION
**Pull request by GammaGames**
This is an initial design, very open to feedback! I made the transitions more OOP, it shouldn't be too hard to add custom imagetable transitions or sliding images. It also has the benefit of being generic so it can be used outside of the scene system, if you just need a quick transition within a scene

### CODE REVIEW

**Comment by GammaGames** [comment]
It's also backwards compatible, behind the scenes it's changed a bit but I still left the public functions intact (with a few extra params sometimes). 

One current issue is into transitions when there's not an initial scene. I did something weird there when there's no mid transition

**Comment by GammaGames** [comment]
I'm still not sure if the transition from null scene works, it's hard to test, but I added cross dissolve

**Comment by Mark-LaCroix** [comment]
Thrilled that you were able to tackle this. I am really swamped at the moment, but I want to get to this, so please bug me (via Discord probably) if I don't get to reviewing this in the next two weeks.

**Comment by GammaGames** [comment]
All but nexus done to match parity! Then a custom imagetable version and a few tweaks to get the pr ready

playdate-20231016-143823

**Comment by GammaGames** [comment]
Okay I think it's ready. I changed the transition to draw into a context so it wouldn't taint the global drawing context, and from my testing it should be backwards compatible

**Comment by GammaGames** [comment]
I also marked https://github.com/NobleRobot/NobleEngine-ProjectTemplate/pull/9 as a draft because it has the new examples, here's a gif of them all:
playdate-20231018-223450

**Comment by Mark-LaCroix** [comment]
**This is looking great!** But, it does break a few things.

You removed but re-implimented the `TransitionType` constants for backwards-compatibility reasons, but you changed their type, which technically breaks compatibility more than just removing them would. In this case, though, your updates to this system are worth losing some backwards-compatibility over, so we can toss out those constants. We do need each transition class to have a human-readable string name, though (for user debugging/profiling, if nothing else). Those constants served that purpose, but they no longer make sense, so I'll work out how to best get that functionality back.

I also want to do a little tidying up, mostly naming convention stuff, but also I want to simplify the class structure a bit (transitions can extend from `Noble.Transition` rather than "Noble.Transition.BaseTransition` I think), and put the engine-included transitions back out into their own file, especially now that you've nicely organized their logic into classes. It will establish a standard for users to mimic as they create their own custom transitions (and make documentation easier).

I'm going to work on this some more tomorrow and see if I can roll it all up over the weekend. This is super good stuff, well done!

**Comment by Mark-LaCroix** [comment]
I especially love some of the little touches like providing dither arguments for transitions that use them.

**Comment by GammaGames** [comment]
>  so we can toss out those constants

YES!! I mostly left them in so people that were using the old transition system *probably* wouldn't have any breaking changes if they updated without checking changelog. I think you can get the text name of a class in an object's `super` property, you'll have to `printTable` to check though because I don't usually mess with class names.

Thanks for looking at it, looking forward to the updates!

**Comment by Mark-LaCroix** [comment]
> I mostly left them in so people that were using the old transition system _probably_ wouldn't have any breaking changes if they updated without checking changelog.

I understand the impulse to "half-preserve" things, but because Lua is a dynamically-typed language, it's _extremely_ important to be careful about this stuff. Changing the type of a previously named variable (in any language) can produce errors that are _much_ more difficult to debug than a simple ~~null~~ nil reference exception.

With this change, projects expecting those values to be a string, like the official template project for example, would get a `bad argument` error. If you weren't familiar with how the engine was built, this would be very difficult to understand and adjust for, especially since the API hadn't technically changed. It also breaks naming convention, since SNAKE_CASE_ALL_CAPS is reserved for string constants.

When introducing breaking changes, a clean break is the best kind, always.

Still hammering it into shape. Maybe it won't be done tonight, but soon!

**Comment by Mark-LaCroix** [comment]
Okay, made a lot of updates in the last commits. No documentation yet (that's going to take forever), but it's working more as designed now. It introduces breaking changes to `Noble.transition()` and `Noble.new()` in order to support transitions with differing amounts of arguments.

I also more distinctly split in-out transitions, so you can have separate easing functions for each, etc. I suppose I should also allow for different duration for in and out....

The idea is to have a simple and intuitive API for making new transitions. I don't know if it's there yet, so I might rename some things or move more stuff around, but I like where it's going, kicked off strongly by the original PR.

Anyway, taking longer than I thought, and still work to do before merging into `main`, but going well!

**Comment by Mark-LaCroix** [comment]
Okay, time to merge. I need to get this into `main` in order to run LDoc since I don't have it installed locally anymore. So, if the documentation doesn't render correctly there will be fixes, but it will be on the `main` branch going forward.

This introduces a few breaking changes, so I'll need to prep an announcement post or something, too.

**Comment by GammaGames** [comment]
🎉🎉🎉 Thank you so much for all the extra work!

**Pull request merged**
